project_id = "yoeisnlqclkdhxutfguq"

[functions.create-naq-questionnaire]
verify_jwt = true

[functions.create-complete-naq]
verify_jwt = true

[functions.seed-naq-questions]
verify_jwt = true

[functions.create-client-account]
verify_jwt = true

[functions.create-coaching-intake]
verify_jwt = true

[functions.process-coaching-intake-submission]
verify_jwt = false

[functions.analyze-body-composition]
verify_jwt = true

[functions.seed-micronutrient-questionnaire]
verify_jwt = true

[functions.calculate-micronutrient-assessment]
verify_jwt = true
